# Generated by Django 5.1.4 on 2024-12-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('slug', models.SlugField(blank=True, default=None, max_length=55, null=True, unique=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True, help_text='Marque para exibir no site')),
            ],
        ),
    ]
